# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/johna/ece-385/lab_6_2/lab_6_2.srcs/sources_1/bd/ml_block/ip/ml_block_microblaze_0_axi_intc_0/ml_block_microblaze_0_axi_intc_0.xci
# IP: The module: 'ml_block_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johna/ece-385/lab_6_2/lab_6_2.gen/sources_1/bd/ml_block/ip/ml_block_microblaze_0_axi_intc_0/ml_block_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ml_block_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johna/ece-385/lab_6_2/lab_6_2.gen/sources_1/bd/ml_block/ip/ml_block_microblaze_0_axi_intc_0/ml_block_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ml_block_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johna/ece-385/lab_6_2/lab_6_2.gen/sources_1/bd/ml_block/ip/ml_block_microblaze_0_axi_intc_0/ml_block_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ml_block_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/johna/ece-385/lab_6_2/lab_6_2.srcs/sources_1/bd/ml_block/ip/ml_block_microblaze_0_axi_intc_0/ml_block_microblaze_0_axi_intc_0.xci
# IP: The module: 'ml_block_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johna/ece-385/lab_6_2/lab_6_2.gen/sources_1/bd/ml_block/ip/ml_block_microblaze_0_axi_intc_0/ml_block_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ml_block_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johna/ece-385/lab_6_2/lab_6_2.gen/sources_1/bd/ml_block/ip/ml_block_microblaze_0_axi_intc_0/ml_block_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ml_block_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johna/ece-385/lab_6_2/lab_6_2.gen/sources_1/bd/ml_block/ip/ml_block_microblaze_0_axi_intc_0/ml_block_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ml_block_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
