# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/ml_block/ml_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block || ORIG_REF_NAME==ml_block} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_microblaze_0_0/ml_block_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_microblaze_0_0 || ORIG_REF_NAME==ml_block_microblaze_0_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_dlmb_v10_0/ml_block_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_dlmb_v10_0 || ORIG_REF_NAME==ml_block_dlmb_v10_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_ilmb_v10_0/ml_block_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_ilmb_v10_0 || ORIG_REF_NAME==ml_block_ilmb_v10_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_dlmb_bram_if_cntlr_0/ml_block_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==ml_block_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_ilmb_bram_if_cntlr_0/ml_block_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==ml_block_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_lmb_bram_0/ml_block_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_lmb_bram_0 || ORIG_REF_NAME==ml_block_lmb_bram_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_xbar_0/ml_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_xbar_0 || ORIG_REF_NAME==ml_block_xbar_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_microblaze_0_axi_periph_0/ml_block_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_microblaze_0_axi_periph_0 || ORIG_REF_NAME==ml_block_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_microblaze_0_axi_intc_0/ml_block_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_microblaze_0_axi_intc_0 || ORIG_REF_NAME==ml_block_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_mdm_1_0/ml_block_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_mdm_1_0 || ORIG_REF_NAME==ml_block_mdm_1_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_clk_wiz_1_0/ml_block_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_clk_wiz_1_0 || ORIG_REF_NAME==ml_block_clk_wiz_1_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_rst_clk_wiz_1_100M_0/ml_block_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==ml_block_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_axi_uartlite_0_0/ml_block_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_axi_uartlite_0_0 || ORIG_REF_NAME==ml_block_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_axi_gpio_0_1/ml_block_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_axi_gpio_0_1 || ORIG_REF_NAME==ml_block_axi_gpio_0_1} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_axi_gpio_0_2/ml_block_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_axi_gpio_0_2 || ORIG_REF_NAME==ml_block_axi_gpio_0_2} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_axi_gpio_0_3/ml_block_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_axi_gpio_0_3 || ORIG_REF_NAME==ml_block_axi_gpio_0_3} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_axi_timer_0_0/ml_block_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_axi_timer_0_0 || ORIG_REF_NAME==ml_block_axi_timer_0_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_axi_quad_spi_0_0/ml_block_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_axi_quad_spi_0_0 || ORIG_REF_NAME==ml_block_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/ml_block/ip/ml_block_xlconcat_0_0/ml_block_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ml_block_xlconcat_0_0 || ORIG_REF_NAME==ml_block_xlconcat_0_0} -quiet] -quiet

# XDC: C:/Users/johna/Tetris-FPGA/tetris/tetris.gen/sources_1/bd/ml_block/ml_block_ooc.xdc
